# User_Model
post_url= https://petstore.swagger.io/v2/user
get_url= https://petstore.swagger.io/v2/user/{username}
put_url= https://petstore.swagger.io/v2/user/{username}
delete_url= https://petstore.swagger.io/v2/user/{username}
get_login_url= https://petstore.swagger.io/v2/user/login
get_logout_url= https://petstore.swagger.io/v2/user/logout

# Store_Model
	# Here we can add Store url's
pet_post_url= https://petstore.swagger.io/v2/pet


# Pet_Model
	# Here we can add Pet url's

